baseURL = 'https://www.cirrus.ac.uk'
languageCode = 'en-us'
title = 'Cirrus'
theme = 'universal'

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Define the number of posts per page
[pagination]
    pagerSize = 10

[params]
    dropdown_mouse_over = false
    logo = "img/cirrus-small.png"
    logo_small = "img/cirrus-icon.png"
    style = "cirrus"
    date_format = "02 Jan 2006"

    about_us = "<p>EPCC provides world-class supercomputing and data services and facilities for science and business.</p>"
    copyright = "Copyright (c) 2025, EPCC; all rights reserved."

    address = "<p><a href='mailto:support@cirrus.ac.uk' alt='email the Cirrus service desk'>support@cirrus.ac.uk</a></p>"

#########################
# Top level website menu
#########################
# About menu
[menu]
[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/about/"
    weight     = 1

[[menu.main]]
    name       = "Overview"
    url        = "/about/"
    weight     = 1
    parent     = "menu.about"

[[menu.main]]
    name       = "Hardware and Software"
    url        = "/about/hardware-software/"
    weight     = 2
    parent     = "menu.about"

[[menu.main]]
    name       = "Research"
    url        = "/about/research/"
    weight     = 3
    parent     = "menu.about"

[[menu.main]]
    name       = "Service Policies"
    url        = "/about/policies/"
    weight     = 4
    parent     = "menu.about"

[[menu.main]]
    name       = "Service News"
    url        = "/about/news/"
    weight     = 5
    parent     = "menu.about"

# Support menu
[[menu.main]]
    name       = "Support and Access"
    identifier = "menu.support"
    url        = "/support-access/"
    weight     = 2

[[menu.main]]
    name       = "Service Status"
    url        = "/support-access/status/"
    weight     = 1
    parent     = "menu.support"

[[menu.main]]
    name       = "Get Access to Cirrus"
    url        = "/support-access/access/"
    weight     = 2
    parent     = "menu.support"

[[menu.main]]
    name       = "User Support"
    url        = "/support-access/user-support/"
    weight     = 3
    parent     = "menu.support"

# Documentation menu
[[menu.main]]
    name       = "Documentation"
    identifier = "menu.documentation"
    url        = "/docs/"
    weight     = 3

[[menu.main]]
    name       = "Cirrus Documentation"
    url        = "/docs/cirrus-docs/"
    weight     = 1
    parent     = "menu.documentation"

[[menu.main]]
    name       = "SAFE Documentation"
    url        = "https://epcced.github.io/safe-docs/"
    weight     = 2
    parent     = "menu.documentation"

# Industry menu
[[menu.main]]
    name       = "Industry"
    identifier = "menu.industry"
    url        = "/industry/"
    weight     = 4

# SAFE login link
[[menu.main]]
    name       = "SAFE Login"
    identifier = "menu.safe"
    url        = "https://safe.epcc.ed.ac.uk"
    weight     = 5

#########################
# Top level carousel setup
#########################
[params.carouselHomepage]
    # All carousel items are defined in their own files
    # at 'data/carousel'.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    text = """
    <div class="description">
    <img class='front-logos' src='img/logo-set.png' alt='Logos' />
    <p class="frontpage">
    Cirrus is a state of the art HPC system hosted by <a href='https://www.epcc.ed.ac.uk/' alt='EPCC website'>EPCC</a>
    at <a href='https://www.ed.ac.uk' alt='University of Edinburgh website'>the University of Edinburgh</a> that provides
    an ideal platform for users in academia and industry to solve their computational, simulation, modelling, and
    data science challenges.<br/><br/>
    Cirrus is also one of the <a href='https://www.ukri.org/' alt='UKRI website'>UKRI</a> Tier-2 national HPC facilities
    and is also supported through the <a href='https://esescityregiondeal.org.uk/' alt='Edinburgh and South East Scotland City Region Deal website'>Edinburgh and South East Scotland City Region Deal</a>.
    </p>
    </div>
    """
    cols = 3 # Default: 3, Available values 2,3,4,6
